environment:
  sdk: ">=3.0.0 <4.0.0"

name: string_art_generator
description: A new Flutter project to generate string art patterns.

dependencies:
  flutter:
    sdk: flutter

flutter:
  assets:
    - assets/
